// Synthetic eligibility examples based on the pinned client's URI matcher,
// never addresses fetched during these tests. Exact/StartsWith use raw strings.
// https://github.com/bitwarden/clients/blob/8246ae9c9a484a0a69f8b27203034555fb872523/libs/common/src/vault/models/view/login-uri.view.ts
export const uriMatchCases = [
  {
    label: "domain subdomain",
    match: 0,
    uri: "https://example.com/login",
    target: "https://auth.example.com/path",
    matched: true,
  },
  {
    label: "domain scheme and port",
    match: 0,
    uri: "https://example.com",
    target: "http://example.com:8080/path",
    matched: true,
  },
  {
    label: "domain unrelated sibling",
    match: 0,
    uri: "https://example.com",
    target: "https://example.net/",
    matched: false,
  },
  {
    label: "domain deceptive suffix",
    match: 0,
    uri: "https://example.com",
    target: "https://example.com.evil.test/",
    matched: false,
  },
  {
    label: "domain country-code suffix",
    match: 0,
    uri: "https://account.example.co.uk",
    target: "https://auth.example.co.uk/",
    matched: true,
  },
  {
    label: "domain country-code unrelated",
    match: 0,
    uri: "https://example.co.uk",
    target: "https://other.co.uk/",
    matched: false,
  },
  {
    label: "domain private GitHub same tenant",
    match: 0,
    uri: "https://alice.github.io",
    target: "https://auth.alice.github.io/",
    matched: true,
  },
  {
    label: "domain private GitHub other tenant",
    match: 0,
    uri: "https://alice.github.io",
    target: "https://bob.github.io/",
    matched: false,
  },
  {
    label: "domain private S3 other tenant",
    match: 0,
    uri: "https://alice.s3.amazonaws.com",
    target: "https://bob.s3.amazonaws.com/",
    matched: false,
  },
  {
    label: "domain public suffix alone",
    match: 0,
    uri: "https://co.uk",
    target: "https://other.co.uk/",
    matched: false,
  },
  {
    label: "domain private suffix alone",
    match: 0,
    uri: "https://github.io",
    target: "https://alice.github.io/",
    matched: false,
  },
  {
    label: "domain Unicode and punycode",
    match: 0,
    uri: "https://bücher.de",
    target: "https://auth.xn--bcher-kva.de/",
    matched: true,
  },
  {
    label: "domain trailing root dot",
    match: 0,
    uri: "https://example.com",
    target: "https://example.com./",
    matched: true,
  },
  {
    label: "domain bare stored hostname",
    match: 0,
    uri: "example.com",
    target: "https://auth.example.com/",
    matched: true,
  },
  {
    label: "domain localhost equality",
    match: 0,
    uri: "http://localhost:8080",
    target: "http://localhost:8081/",
    matched: true,
  },
  {
    label: "domain localhost versus IP",
    match: 0,
    uri: "http://localhost",
    target: "http://127.0.0.1/",
    matched: false,
  },
  {
    label: "domain IP equality",
    match: 0,
    uri: "http://127.0.0.1:8080",
    target: "http://127.0.0.1:8081/",
    matched: true,
  },
  {
    label: "domain distinct IP",
    match: 0,
    uri: "http://127.0.0.1",
    target: "http://127.0.0.2/",
    matched: false,
  },
  {
    label: "domain IPv6 canonical equality",
    match: 0,
    uri: "http://[0:0:0:0:0:0:0:1]",
    target: "http://[::1]:8080/",
    matched: true,
  },
  {
    label: "domain blacklisted script host",
    match: 0,
    uri: "https://google.com",
    target: "https://script.google.com/",
    matched: false,
  },
  {
    label: "domain Google ordinary host",
    match: 0,
    uri: "https://google.com",
    target: "https://accounts.google.com/",
    matched: true,
  },
  {
    label: "host scheme and path ignored",
    match: 1,
    uri: "https://auth.example.com:4000/login",
    target: "http://auth.example.com:4000/path?q=x#hash",
    matched: true,
  },
  {
    label: "host port differs",
    match: 1,
    uri: "https://auth.example.com:4000",
    target: "https://auth.example.com:5000/",
    matched: false,
  },
  {
    label: "host missing port differs",
    match: 1,
    uri: "https://auth.example.com:4000",
    target: "https://auth.example.com/",
    matched: false,
  },
  {
    label: "host subdomain differs",
    match: 1,
    uri: "https://auth.example.com",
    target: "https://sub.auth.example.com/",
    matched: false,
  },
  {
    label: "host parent differs",
    match: 1,
    uri: "https://auth.example.com",
    target: "https://example.com/",
    matched: false,
  },
  {
    label: "host default port normalized",
    match: 1,
    uri: "https://EXAMPLE.COM:443/login",
    target: "https://example.com/path",
    matched: true,
  },
  {
    label: "host trailing dot differs",
    match: 1,
    uri: "https://example.com",
    target: "https://example.com./",
    matched: false,
  },
  {
    label: "host bare stored hostname",
    match: 1,
    uri: "example.com:8080",
    target: "http://example.com:8080/",
    matched: true,
  },
  {
    label: "host explicit script domain allowed",
    match: 1,
    uri: "https://script.google.com",
    target: "https://script.google.com/",
    matched: true,
  },
  {
    label: "exact same string",
    match: 3,
    uri: "https://example.com/login?a=1#part",
    target: "https://example.com/login?a=1#part",
    matched: true,
  },
  {
    label: "exact query differs",
    match: 3,
    uri: "https://example.com/login",
    target: "https://example.com/login?a=1",
    matched: false,
  },
  {
    label: "exact fragment differs",
    match: 3,
    uri: "https://example.com/login",
    target: "https://example.com/login#part",
    matched: false,
  },
  {
    label: "exact host case preserved",
    match: 3,
    uri: "https://EXAMPLE.COM/login",
    target: "https://example.com/login",
    matched: false,
  },
  {
    label: "exact path case preserved",
    match: 3,
    uri: "https://example.com/Login",
    target: "https://example.com/login",
    matched: false,
  },
  {
    label: "exact explicit default port preserved",
    match: 3,
    uri: "https://example.com:443/login",
    target: "https://example.com/login",
    matched: false,
  },
  {
    label: "exact dot segments preserved",
    match: 3,
    uri: "https://example.com/a/../login",
    target: "https://example.com/login",
    matched: false,
  },
  {
    label: "prefix path",
    match: 2,
    uri: "https://example.com/path/",
    target: "https://example.com/path/child",
    matched: true,
  },
  {
    label: "prefix missing trailing slash",
    match: 2,
    uri: "https://example.com/path/",
    target: "https://example.com/path",
    matched: false,
  },
  {
    label: "prefix interrupted by port",
    match: 2,
    uri: "https://example.com/path/",
    target: "https://example.com:8443/path/child",
    matched: false,
  },
  {
    label: "prefix raw case",
    match: 2,
    uri: "https://EXAMPLE.COM/path/",
    target: "https://example.com/path/child",
    matched: false,
  },
  {
    label: "prefix dangerous hostname extension",
    match: 2,
    uri: "https://example.com",
    target: "https://example.com.evil.test/",
    matched: true,
  },
  {
    label: "never identical target",
    match: 5,
    uri: "https://example.com/login",
    target: "https://example.com/login",
    matched: false,
  },
  {
    label: "domain unrelated trailing-root-dot hosts",
    match: 0,
    uri: "https://example.com.",
    target: "https://other.com./",
    matched: false,
  },
] as const;
